### ISSUE TITLE
 Safari problems: leaflet images don't load in either template and details aren't spaced out

### ISSUE THREAD

**Issue by kjell** [artsmia/lume#51]
# https://lume.u100.io/mia/

- [x] Safari problems: leaflet images don't load in either template and [details aren't spaced out](https://user-images.githubusercontent.com/1378/35114056-181bf4a8-fc49-11e7-944a-0ec96b7cc370.png)
- [x] [details "invert" after the "second click"](https://user-images.githubusercontent.com/1378/35113993-e897c19e-fc48-11e7-8b16-1f5e85267d4b.png) - when successive highlighted regions overlap?
- [x] "more" loading doesn't work after interacting with template (original,slider) checkboxes on landing page (something to do with `&search=` in the URL - with that removed it does work)
- [x] ["more" content is placeholder`ed in original template](https://user-images.githubusercontent.com/1378/35114130-5210654a-fc49-11e7-8fa0-b58f818936ee.png)
- [x] [leaflet tiles have a tiny gap between them](https://user-images.githubusercontent.com/1378/35114173-7b8ffc0a-fc49-11e7-94aa-33ebec1aac72.png)

**Comment by carlpeaslee** [comment]
re: "Safari problems: leaflet images don't load in either template and details aren't spaced out":

I'm not able to replicate this one... We will have to check it out in person.

**Comment by carlpeaslee** [comment]
re: leaflet tiles have tiny gaps: yeah, I'm having a hard time solving this one. I know it has to do with this issue: https://github.com/Leaflet/Leaflet/issues/3575.

**Comment by carlpeaslee** [comment]
tile gaps is resolved
