### ISSUE TITLE
Add room filtering / Gallery Maps 

### ISSUE THREAD

**Issue by carlpeaslee** [artsmia/lume#56]

**Comment by carlpeaslee** [comment]
[Art Stories Draft.pdf](https://github.com/artsmia/lume/files/1686816/Art.Stories.Draft.pdf)

**Comment by carlpeaslee** [comment]
@kjell was there a link for that json that listed the different clusters?

**Comment by kjell** [comment]
https://github.com/artsmia/griot/blob/master/clusters/clusters.json
