### ISSUE TITLE
Setup Video Component to play simple video link with html element

### ISSUE THREAD

**Issue by carlpeaslee** [artsmia/lume#59]

**Comment by carlpeaslee** [comment]
ask @kjell about the best way to get thumbnail for videos

**Comment by kjell** [comment]
All videos will have a URL like  https://cdn.dx.artsmia.org/videos/MakingBeerPotsClay.mp4 with a corresponding thumbnail JPG at https://cdn.dx.artsmia.org/videos/MakingBeerPotsClay.mp4.jpg
